version: '2'

services:

 app:
  build:
    context: ./
    dockerfile: app.dockerfile
  volumes:
    - ./:/var/www/html

 nginx:
  build: 
    context: ./
    dockerfile: nginx.dockerfile
  volumes_from:
    - app
  ports:
   - 3000:80
  # depends_on:
  #  - app

 mysql:
  image: mariadb:10.4
  ports:
   - 3307:3306
  environment:
    MYSQL_ROOT_PASSWORD: example
    MYSQL_USER: test
    MYSQL_PASSWORD: test
    MYSQL_DATABASE: test